### ISSUE TITLE
Using PD2 Linux "bundle_db.blb" does not show all files

### ISSUE THREAD

**Issue by dribbleondo** [Luffyyy/DieselBundleViewer#4]
Forcing 0-byte files to be visible shows the files, but they cannot be viewed or extracted. I noticed the same issue with Bundle Modder (as that extracts ~5.5GB out of the almost 70GB Payday 2 actually is) so clearly there's a problem with how the blb is being read, not that most files in DBV cannot be extracted.

**Comment by Luffyyy** [comment]
This is odd. Last I checked on mint ot worked just fine. You cannot drag but you can extract it and view some. Not much I can do right now. I'll test it later on my manjaro install.

**Comment by dribbleondo** [comment]
Thank you =)

**Comment by Luffyyy** [comment]
I was using the release too.

**Comment by Luffyyy** [comment]
Seems to work for me. Note that some things like scriptdata are broken atm.

**Comment by dribbleondo** [comment]
@Luffyyy Sorry for the ping, but I got some time to sorta show off what I mean[Here's what I see when I force 0-byte files, and look up "texture"](https://drive.google.com/file/d/15HNdeg-FIEWZRSuq0XNSAfvmppXjKjTa/view?usp=sharing)

I've tried seeing if the hashlist was incorrectly formatted (turns out DBV seems to not care which way "/" is), and at this point, i'm at a loss as to what I'm doing wrong.

**Comment by dribbleondo** [comment]
> Seems to work for me. Note that some things like scriptdata are broken atm.

Okay, something of a lightbulb moment; it appears none of the all_X.bundles are being read by DBV.

**Comment by Luffyyy** [comment]
It'll be hard if not impossible to fix it without a Linux dual boot (which I currently don't have) plus time constraint so I'm not really sure plus there's the fact I haven't touched that code for quite a while.

**Comment by connieprice** [comment]
I'm going to do a brief investigation into this as I should have a copy of the PD2 linux build lying on a VM somewhere.

**Comment by dribbleondo** [comment]
This might be worth looking at again @connieprice @Luffyyy as the new move to .net 5 might make this easier.

**Comment by RedFlamer** [comment]
This also applies for the latest console builds of PD2 which use similar x64 multi-bundle headers

**Comment by dribbleondo** [comment]
Now I can die happily.

**Comment by Luffyyy** [comment]
Released the update with the change on both MWS and GitHub.

**Comment by dribbleondo** [comment]
![image](https://user-images.githubusercontent.com/9034161/213681016-de28692c-e06b-4e22-b4c8-e96e7fddfbd1.png)
Now I can die extra happy =D Thanks @RedFlamer !
